# Generated by Django 3.1.7 on 2021-05-27 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kiosk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('price', models.FloatField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField()),
                ('ordered_at', models.DateTimeField(blank=True, null=True)),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card')], max_length=4)),
                ('cust_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kiosk.customer')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kiosk.food')),
            ],
        ),
    ]
